version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.2.10
    - 8.2.8
    - 8.2.9
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.3.3
